# Generated by Django 5.2.13 on 2026-06-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_etudiantprofile_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantprofile',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='etudiantprofile',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='prénom'),
        ),
    ]
