# Generated by Django 5.2.13 on 2026-06-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_etudiantprofile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantprofile',
            name='annee_courante',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='année courante'),
        ),
        migrations.AddField(
            model_name='etudiantprofile',
            name='nni',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='NNI'),
        ),
    ]
