databases:
  - name: sehily-db
    databaseName: sehily
    user: sehily
    plan: free
    region: oregon

services:
  - type: web
    name: sehily-backend
    env: python
    plan: free
    region: oregon
    buildCommand: "cd backend && bash build.sh"
    startCommand: "cd backend && python manage.py migrate && python manage.py create_default_admin && python manage.py seed_annee_universitaire && python manage.py seed_etudiants_reference && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: sehily-db
          property: internalConnectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://dijajaja.github.io"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
