# Generated by Django 5.2.13 on 2026-04-18 19:23

import django.db.models.deletion
import dossiers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierBourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_INSTRUCTION', 'En instruction'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('COMPLEMENT_DEMANDE', 'Complément demandé')], default='BROUILLON', max_length=30)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='referentials.anneeuniversitaire')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_bourse', to=settings.AUTH_USER_MODEL)),
                ('instructeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_instruits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dossier de bourse',
                'verbose_name_plural': 'dossiers de bourse',
                'ordering': ('-cree_le',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to=dossiers.models.document_upload_path)),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers.dossierbourse')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DossierHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=30)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='dossiers.dossierbourse')),
            ],
            options={
                'verbose_name': 'entrée d’historique dossier',
                'ordering': ('-date_action',),
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_COURS', 'En cours'), ('EN_ATTENTE_ETUDIANT', 'En attente étudiant'), ('TRAITEE', 'Traitée'), ('REJETEE', 'Rejetée')], default='SOUMISE', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('dossiers', models.ManyToManyField(blank=True, related_name='reclamations', to='dossiers.dossierbourse')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réclamation',
                'verbose_name_plural': 'réclamations',
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='MessageReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('piece_jointe', models.CharField(blank=True, max_length=512)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_reclamation', to=settings.AUTH_USER_MODEL)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dossiers.reclamation')),
            ],
            options={
                'verbose_name': 'message de réclamation',
                'verbose_name_plural': 'messages de réclamation',
                'ordering': ('date_envoi',),
            },
        ),
    ]
