# Generated by Django 5.2.13 on 2026-04-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierbourse',
            name='montant_bourse',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la bourse (utilisé pour générer les paiements une fois le dossier validé).', max_digits=12),
        ),
    ]
