# Generated by Django 5.2.13 on 2026-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeUniversitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('est_courante', models.BooleanField(default=False, help_text='Une seule année devrait être marquée comme courante.')),
            ],
            options={
                'verbose_name': 'année universitaire',
                'verbose_name_plural': 'années universitaires',
                'ordering': ('-date_debut',),
            },
        ),
    ]
