# Generated by Django 5.2.13 on 2026-06-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nni', models.CharField(db_index=True, max_length=20, unique=True)),
                ('matricule', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('etablissement', models.CharField(max_length=255)),
                ('formation', models.CharField(max_length=255)),
                ('annee_courante', models.CharField(max_length=16)),
                ('est_eligible', models.BooleanField(default=False)),
                ('motif_non_eligibilite', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'référence étudiant',
                'verbose_name_plural': 'références étudiants',
                'ordering': ('matricule',),
            },
        ),
    ]
