# Generated by Django 5.2.13 on 2026-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentials', '0002_etudiantreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantreference',
            name='wilaya',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='wilaya'),
        ),
    ]
