# Generated by Django 5.2.13 on 2026-06-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentials', '0003_add_wilaya_to_etudiant_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantreference',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
    ]
