# Generated by Django 5.2.13 on 2026-04-18 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0002_dossierbourse_montant_bourse'),
        ('referentials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeBeneficiaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('periode', models.CharField(blank=True, max_length=64)),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listes_beneficiaires', to='referentials.anneeuniversitaire')),
                ('partenaire', models.ForeignKey(blank=True, limit_choices_to={'role': 'PARTENAIRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'liste de bénéficiaires',
                'verbose_name_plural': 'listes de bénéficiaires',
                'ordering': ('-date_generation',),
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EFFECTUE', 'Effectué'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('date_operation', models.DateTimeField(blank=True, null=True)),
                ('reference_externe', models.CharField(blank=True, max_length=128)),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='referentials.anneeuniversitaire')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='dossiers.dossierbourse')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='payments.listebeneficiaires')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ('liste', 'id'),
                'constraints': [models.UniqueConstraint(fields=('liste', 'dossier'), name='uniq_paiement_liste_dossier')],
            },
        ),
    ]
